//****************************************************************************
//**
//**    GF1.cpp
//**    Defines the entry point for the DLL application.
//**
//**    Copyright (c) 2003 QANTM CMC Australia
//**
//**    Author:  Dale Freya (Autogenerated by Visual Studio)
//**    Created: 21/09/2003
//**
//****************************************************************************
#include "GF1_stdafx.h"
#include <GF1.h>
#include <../src/GF1_Texture_Manager.h>

#ifdef _DEBUG
#define GF1_API_VERSION_STRING "Game Framework 1 (Version "##GF1_API_VERSION##") Debug"
#else
#define GF1_API_VERSION_STRING "Game Framework 1 (Version "##GF1_API_VERSION##") Release"
#endif

   namespace GF1
   {

      GF1_API const char *GetVersion()
      {
         return GF1_API_VERSION_STRING;
      }

	  
	  void GF1_API ReleaseAllTexture()
	  {
		  GF1::TextureManager::Instance().CacheOut();
	  }

   }



BOOL APIENTRY DllMain(
   HANDLE /* hModule */, 
   DWORD  ul_reason_for_call, 
   LPVOID /* lpReserved */)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
	case DLL_THREAD_ATTACH:
	case DLL_THREAD_DETACH:
	case DLL_PROCESS_DETACH:
		break;
	}
    return TRUE;
}



//****************************************************************************
//**
//**    END IMPLEMENTATION
//**
//****************************************************************************
