//****************************************************************************
//**
//**    GF1_stdafx.h
//**    Include file for standard system include files, or project specific 
//**    include files that are used frequently, but are changed infrequently.
//**
//**    Copyright (c) 2003 QANTM CMC Australia
//**
//**    Author:  Dale Freya (Autogenerated by Visual Studio)
//**    Created: 21/09/2003
//**
//****************************************************************************
#pragma once

// Exclude rarely-used stuff from Windows headers
#define WIN32_LEAN_AND_MEAN		
// Windows headers give warnings with level 4 so reduce the warning level to 3
// around the windows headers
#pragma warning( push, 3 )

// FMOD (Sound Library) Header Files
#include <fmod.h>
// #include <fmod_errors.h>

// Devil (Image Library) Header Files
#include "il/il.h"
#include "il/ilu.h"

// Windows Header Files
#include <windows.h>
#include <mmsystem.h>

// Restore the warning level
#pragma warning( pop )

// OpenGL Headers
#include <gl/gl.h>

// C++ Header Files
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <fstream>
#include <iostream>
#include <cmath>

//****************************************************************************
//**
//**    END INTERFACE
//**
//****************************************************************************

