//****************************************************************************
//**
//**    GF1_stdafx.cpp
//**    Source file that includes just the standard includes 
//**    GF1.pch will be the pre-compiled header stdafx.obj 
//**    will contain the pre-compiled type information.
//**
//**    Copyright (c) 2003 QANTM CMC Australia
//**
//**    Author:  Dale Freya (Autogenerated by Visual Studio)
//**    Created: 21/09/2003
//**
//****************************************************************************

#include "GF1_stdafx.h"

// TODO: reference any additional headers you need in STDAFX.H
// and not in this file

//****************************************************************************
//**
//**    END IMPLEMENTATION
//**
//****************************************************************************
