#ifndef GF1_DEF_H
#define GF1_DEF_H
//****************************************************************************
//**
//**    GF1_Def.h
//**    BIE Game Framework 1 Definitions
//**
//**    Copyright (c) 2003 QANTM CMC Australia
//**
//**    Author:  Dale Freya (Autogenerated by Visual Studio)
//**    Created: 21/09/2003
//**
//**    Dale Freya   25/11/2003
//**        *  Added GF1_API_VERSION definition to allow version 
//**           compatibility detection between GF1 headers and dlls.
//****************************************************************************

// ===========================================================================
// GF1_API
// ===========================================================================
// The following ifdef block is the standard way of creating macros which 
// make exporting from a DLL simpler. All files within this DLL are compiled 
// with the GF1_EXPORTS symbol defined on the command line. this symbol 
// should not be defined on any project that uses this DLL. This way any 
// other project whose source files include this file see GF1_API 
// functions as being imported from a DLL, whereas this DLL sees symbols 
// defined with this macro as being exported.
// ===========================================================================
#ifdef GF1_EXPORTS
#define GF1_API __declspec(dllexport)
#else
#define GF1_API __declspec(dllimport)
#endif

// ===========================================================================
// GF1_API_VERSION
// ===========================================================================
// Defines the version of the BIE GF1 API as a c string.
// ===========================================================================
#define GF1_API_VERSION "1.11"


//****************************************************************************
//**
//**    END INTERFACE
//**
//****************************************************************************
#endif
